### ISSUE TITLE
Unzip files

### ISSUE THREAD

**Issue by masl** [B3Crazy/Banksystem#1]
I came across the project and wanted to take a closer look, but there was only one ZIP file.

So I think you could extract the files from the ZIP into this repository, so the source files can be seen easier.

**Comment by Bharat-Thapa** [comment]
I have unzipped the file please approve it in pull request tab

**Comment by masl** [comment]
> I have unzipped the file please approve it in pull request tab

Thanks, but..
I think the compiled `.class` files are not that important, as they are build from the `.java` files' source code.
Maybe a `.gitignore` might be helpful for this as well.

**Comment by Bharat-Thapa** [comment]
Ok will update the changes

**Comment by Bharat-Thapa** [comment]
Done with the changes
